apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  labels:
    app: $APP_NAME-service
    role: master
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: $APP_NAME-deployment
    role: master
    tier: backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 443
    protocol: TCP
    name: https
