apiVersion: v1
kind: Service
metadata:
  name: ngk-certification-service
  labels:
    app: ngk-certification-service
    role: master
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: ngk-certification-deployment
    role: master
    tier: backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
